### ISSUE TITLE
Code Structure

### ISSUE THREAD

**Issue by chop0** [Hallowizer/Unscrew#1]
-4/10. Couldn't tell what was going on. Add interfacing and fix the polymorphism implementation. Also, a lot of your functions would be better with recursion so i would do that ¯\_(ツ)_/¯

**Comment by chop0** [comment]
Also, loading classes at runtime is generally a bad practice

**Comment by Hallowizer** [comment]
Hey, have you EVER looked at the Forge code? I need to load classes at runtime.

**Comment by chop0** [comment]
then dont use forge
